### ISSUE TITLE
redis

### ISSUE THREAD

**Issue by dreamlike-ocean** [dreamlike-ocean/backend_qingyou#6]
1，单机的基础的命令和基础的数据结构，要求说明清楚各个数据结构和api的适用情况，最好附带代码
2，基础的redis java client（比如说lettuce）
3，更进一步的讲解，比如说具体的实现，帮助同学们更好理解redis是如何运行的，同时帮助如何高效使用redis

**Comment by gwtt** [comment]
好的

**Comment by dreamlike-ocean** [comment]
目前完成了
后续打磨等有时间再做，先暂时关闭
